### ISSUE TITLE
Tutorial on https://hub.qovery.com/guides/tutorial/how-to-integrate-qovery-with-github-actions/#add-your-github-action-workflow failed

### ISSUE THREAD

**Issue by pdevito3** [Qovery/documentation#187]
The tutorial on:

https://hub.qovery.com/guides/tutorial/how-to-integrate-qovery-with-github-actions/#add-your-github-action-workflow

Here's what went wrong:

Seems like using the `name` properties (and the project info overall) doesn't work and gives me the following error:
```
Warning: Unexpected input(s) 'qovery-organization-name', 'qovery-project-name', 'qovery-environment-name', 'qovery-application-names', valid inputs are ['entryPoint', 'args', 'qovery-organization-id', 'qovery-environment-id', 'qovery-application-ids', 'qovery-api-token']
Run Qovery/qovery-action@v0.10
  with:
    qovery-organization-name: Paul's Personal
    qovery-project-name: hello-qovery-basic
    qovery-environment-name: pipeline-test-env
    qovery-application-names: hello qovery pipeline
/usr/bin/docker run --name e3051f36601d2646d0938b1de91e65e48d_9723da --label 5364e3 --workdir /github/workspace --rm -e "INPUT_QOVERY-ORGANIZATION-NAME" -e "INPUT_QOVERY-PROJECT-NAME" -e "INPUT_QOVERY-ENVIRONMENT-NAME" -e "INPUT_QOVERY-APPLICATION-NAMES" -e "INPUT_QOVERY-API-TOKEN" -e "INPUT_QOVERY-ORGANIZATION-ID" -e "INPUT_QOVERY-ENVIRONMENT-ID" -e "INPUT_QOVERY-APPLICATION-IDS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/hello-qovery-basic/hello-qovery-basic":"/github/workspace" 5364e3:051f36601d2646d0938b1de91e65e48d  "" "" "" ""
Qovery deployment starting for commit: ff5403fb00d73d0580b7405560d5732a749d73c8 ...
error while trying to get environment status: qovery API error, status code: 401 Unauthorized
```

Once I updated the vars to use the id's (i got the id's from the url path in my application on the console) and removed the project var it worked okay:
```yaml
name: Deploy and Test on Qovery
on:
  workflow_call:
    inputs:
      organization-id:
        required: true
        type: string
      environment-id:
        required: true
        type: string
      application-ids:
        required: true
        type: string
    secrets:
      api-token:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --configuration Release --no-restore
      - name: Run tests
        run: dotnet test --no-restore --verbosity minimal
  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy on Qovery
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy on Qovery
        uses: Qovery/qovery-action@v0.10
        id: qovery
        with:
          qovery-organization-id: ${{ inputs.organization-id }}
          qovery-environment-id: ${{ inputs.environment-id }}
          qovery-application-ids: ${{ inputs.application-ids }}
          qovery-api-token: ${{ secrets.api-token }}
```

```yaml
name: Deploy to dev
on:
  push:
    branches:
      - main
jobs:
  test-and-deploy:
    uses: ./.github/workflows/test-and-deploy.yaml
    with:
      organization-id: guid-for-org
      environment-id: guid-for-env
      application-ids: guid-for-app
    secrets:
      api-token: ${{ secrets.QOVERY_API_TOKEN }}
```
